apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-auth-pvc
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-marketplace
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-marketplace-pvc
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-payment
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-payment-pvc
spec:
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-chat
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "200m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-chat-pvc
spec:
  resources:
    requests:
      storage: 2Gi
