"""empty message

Revision ID: 7a62e69415e0
Revises: c791a74bd01a
Create Date: 2025-05-20 10:25:11.012358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a62e69415e0'
down_revision = 'c791a74bd01a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_system_escrow',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('wallets', 'is_system_fee',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'is_system_fee',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('wallets', 'is_system_escrow',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ### 