"""Add statistics tables

Revision ID: 7e414e300cbb
Revises: 4577029b64c8
Create Date: 2025-05-19 17:03:02.039974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e414e300cbb'
down_revision = '4577029b64c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 