"""Add system wallet fields

Revision ID: c791a74bd01a
Revises: 7e414e300cbb
Create Date: 2025-05-20 10:22:44.772026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c791a74bd01a'
down_revision = '7e414e300cbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('is_system_escrow', sa.Boolean(), nullable=True))
    op.add_column('wallets', sa.Column('is_system_fee', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wallets', 'is_system_fee')
    op.drop_column('wallets', 'is_system_escrow')
    # ### end Alembic commands ### 