# Chat service

apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: gametrade
  labels:
    app: chat-svc
spec:
  selector:
    app: chat-svc
  ports:
    - port: 8003
      targetPort: 8003
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-svc-config
  namespace: gametrade
data:
  .env: |
    DATABASE_URL=postgresql://gametrade:gametrade@postgres-chat:5432/chat_db
    REDIS_URL=redis://redis:6379/3 # Использовать разные БД Redis для разных сервисов
    RABBITMQ_URL=amqp://gametrade:gametrade@rabbitmq:5672/
    AUTH_SERVICE_URL=http://auth-svc:8000
    JWT_SECRET=changeThisInProduction
    SYSTEM_TOKEN=changeSystemToken
    ENVIRONMENT=production
    LOG_LEVEL=INFO
    API_PREFIX=/api
    # SERVICE_SPECIFIC_ENV_VARS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-svc
  namespace: gametrade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-svc
  template:
    metadata:
      labels:
        app: chat-svc
    spec:
      containers:
        - name: chat-svc
          image: gametrade/chat-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
              name: http
          envFrom:
            - configMapRef:
                name: chat-svc-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: chat-svc-config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: chat-svc-config
          configMap:
            name: chat-svc-config 
