apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-auth.yaml
  - postgres-marketplace.yaml
  - postgres-payment.yaml
  - postgres-chat.yaml
  - namespace.yaml
  - redis.yaml
  - rabbitmq.yaml
  - nginx.yaml
  - auth-svc.yaml
  - marketplace-svc.yaml
  - payment-svc.yaml
  - chat-svc.yaml

commonLabels:
  app.kubernetes.io/part-of: gametrade
  app.kubernetes.io/managed-by: kustomize 