# Marketplace service

apiVersion: v1
kind: Service
metadata:
  name: marketplace-svc
  namespace: gametrade
  labels:
    app: marketplace-svc
spec:
  selector:
    app: marketplace-svc
  ports:
    - port: 8001
      targetPort: 8001
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-svc-config
  namespace: gametrade
data:
  .env: |
    DATABASE_URL=postgresql://gametrade:gametrade@postgres-marketplace:5432/marketplace_db
    REDIS_URL=redis://redis:6379/1 # Использовать разные БД Redis для разных сервисов
    RABBITMQ_URL=amqp://gametrade:gametrade@rabbitmq:5672/
    AUTH_SERVICE_URL=http://auth-svc:8000
    CHAT_SERVICE_URL=http://chat-svc:8003
    JWT_SECRET=changeThisInProduction
    SYSTEM_TOKEN=changeSystemToken
    ENVIRONMENT=production
    LOG_LEVEL=INFO
    API_PREFIX=/api
    # SERVICE_SPECIFIC_ENV_VARS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-svc
  namespace: gametrade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketplace-svc
  template:
    metadata:
      labels:
        app: marketplace-svc
    spec:
      containers:
        - name: marketplace-svc
          image: gametrade/marketplace-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              name: http
          envFrom:
            - configMapRef:
                name: marketplace-svc-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: marketplace-svc-config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: marketplace-svc-config
          configMap:
            name: marketplace-svc-config 
