# Payment service

apiVersion: v1
kind: Service
metadata:
  name: payment-svc
  namespace: gametrade
  labels:
    app: payment-svc
spec:
  selector:
    app: payment-svc
  ports:
    - port: 8002
      targetPort: 8002
      name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-svc-config
  namespace: gametrade
data:
  .env: |
    DATABASE_URL=postgresql://gametrade:gametrade@postgres-payment:5432/payment_db
    REDIS_URL=redis://redis:6379/2 # Использовать разные БД Redis для разных сервисов
    RABBITMQ_URL=amqp://gametrade:gametrade@rabbitmq:5672/
    AUTH_SERVICE_URL=http://auth-svc:8000
    MARKETPLACE_SERVICE_URL=http://marketplace-svc:8001
    ENVIRONMENT=production
    LOG_LEVEL=INFO
    API_PREFIX=/api
    # SERVICE_SPECIFIC_ENV_VARS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
  namespace: gametrade
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-svc
  template:
    metadata:
      labels:
        app: payment-svc
    spec:
      containers:
        - name: payment-svc
          image: gametrade/payment-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
              name: http
          envFrom:
            - configMapRef:
                name: payment-svc-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
            - name: payment-svc-config
              mountPath: /app/.env
              subPath: .env
      volumes:
        - name: payment-svc-config
          configMap:
            name: payment-svc-config 
