apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: nginx
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30 