"""Add user auth fields

Revision ID: adf86ca60b74
Revises: 930923f287fd
Create Date: 2025-05-19 16:36:52.824929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf86ca60b74'
down_revision = '930923f287fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String()), server_default="{'user'}", nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ### 