apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace-svc
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-svc
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-svc
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
